#!/bin/bash
# Quick Test Commands - CryptoKnight Processor
# Copy and paste these commands to run tests

echo "=========================================="
echo "CryptoKnight Processor - Quick Test Guide"
echo "=========================================="
echo ""
echo "Available Commands:"
echo ""
echo "1. Run all working tests:"
echo "   cd sim"
echo "   ./run_individual_test.sh tb_karatsuba"
echo "   ./run_individual_test.sh tb_register_bank"
echo "   ./run_individual_test.sh tb_data_memory"
echo ""
echo "2. View waveforms:"
echo "   gtkwave waveforms/tb_karatsuba.vcd"
echo "   gtkwave waveforms/tb_register_bank.vcd"
echo "   gtkwave waveforms/tb_data_memory.vcd"
echo ""
echo "3. Check test results:"
echo "   cat results/tb_karatsuba_sim.log"
echo "   cat results/tb_register_bank_sim.log"
echo "   cat results/tb_data_memory_sim.log"
echo ""
echo "4. List available testbenches:"
echo "   ls -1 testbenches/"
echo ""
echo "5. View test documentation:"
echo "   cat README_TESTS.md"
echo "   cat TEST_RESULTS.md"
echo ""
echo "=========================================="
echo "Currently Working Tests:"
echo "  ✅ tb_karatsuba      - Karatsuba Multiplier (8/8 tests pass)"
echo "  ✅ tb_register_bank  - Register File (35/35 tests pass)"
echo "  ✅ tb_data_memory    - Data Memory (33/33 tests pass)"
echo "=========================================="
